defaults:
    - dataset: cmu_arctic
    - preprocessing: default
    - model: wav2vec_rnn
    - training: wav2vec_rnn

seed: 100
enc_checkpoint: ???
resume: False
pretrain_checkpoint: False
train_list: train.json
val_list: val.json
test_list: test.json
checkpoint_dir: ???
tensorboard_dir: ???
