# @package _group_
batch_size: 32
sample_frames: 32
n_steps: 160000
adam:
    lr: 4e-4
    beta_0: 0.9
    beta_1: 0.999
    eps: 1e-08
    weight_decay: 0
multi_step_lr:
    milestones:
        - 50000
        - 75000
        - 100000
        - 125000
    gamma: 0.5
n_workers: 8
validation_interval: 2
save_interval: 10000
es:
    monitor_value: loss
    direction: min
