# @package _group_
batch_size: 32
sample_frames: 32
n_steps: 50000
tuning_n_steps: 50000
optimizer: adam
adam:
    lr: 4e-4
    beta_0: 0.9
    beta_1: 0.999
    eps: 1e-08
    weight_decay: 0
schedular: multi_step_lr
multi_step_lr:
    milestones:
        - 50000
        - 75000
        - 100000
        - 125000
    gamma: 0.5
checkpoint_interval: 5000
n_workers: 8
log_interval: 1
val_log_interval: 2
